// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrlsDKFQNxR3j0MWXi2601AW_mtgPOYIc',
    appId: '1:778188445770:web:56502f26687c5904c3eeb3',
    messagingSenderId: '778188445770',
    projectId: 'mystock-260a1',
    authDomain: 'mystock-260a1.firebaseapp.com',
    storageBucket: 'mystock-260a1.appspot.com',
    measurementId: 'G-YCHQZ91JXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_P-iidyq4oZhZ5uAYDhPNtK7-hZI2ZfQ',
    appId: '1:778188445770:android:4ec556130069ada0c3eeb3',
    messagingSenderId: '778188445770',
    projectId: 'mystock-260a1',
    storageBucket: 'mystock-260a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhuMum-7UdXVgoItEbSdIPeb1M-r4xYWo',
    appId: '1:778188445770:ios:f367da573e42fdfec3eeb3',
    messagingSenderId: '778188445770',
    projectId: 'mystock-260a1',
    storageBucket: 'mystock-260a1.appspot.com',
    iosBundleId: 'com.example.stock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhuMum-7UdXVgoItEbSdIPeb1M-r4xYWo',
    appId: '1:778188445770:ios:7a9699c80198fb24c3eeb3',
    messagingSenderId: '778188445770',
    projectId: 'mystock-260a1',
    storageBucket: 'mystock-260a1.appspot.com',
    iosBundleId: 'com.example.stock.RunnerTests',
  );
}
